preload = /home/javi_dev/Imágenes/Background/5556661.jpg
wallpaper = HDMI-A-2,/home/javi_dev/Imágenes/Background/5556661.jpg

env = GDK_DPI_SCALE,1.25
env = QT_SCALE_FACTOR,1.25
env = QT_FONT_DPI,120
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
