preload = /home/javi_dev/dev/config/dotfiles/hypr/walls/2.png
wallpaper = HDMI-A-2,/home/javi_dev/dev/config/dotfiles/hypr/walls/2.png

# Efectos y configuraciones mejoradas
splash = true
splash_offset = 2.0
ipc = on
